name: Auto Build & Release
on:
  workflow_dispatch:
  schedule:
  - cron: '0,30 * * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y wget

      - name: Get latest official version
        id: upstream
        run: |
          TAG=$(curl -s https://api.github.com/repos/anomalyco/opencode/releases/latest | jq -r '.tag_name')
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      # 构建 普通版 x64（强制传递 normal 参数）
      - name: Build normal x86_64
        run: |
          chmod +x build/build.sh
          ./build/build.sh ${{ steps.upstream.outputs.TAG }} x86_64 normal

      # 构建 普通版 arm64
      - name: Build normal arm64
        run: |
          ./build/build.sh ${{ steps.upstream.outputs.TAG }} arm64 normal

      # 构建 musl版 x64
      - name: Build musl x86_64
        run: |
          ./build/build.sh ${{ steps.upstream.outputs.TAG }} x86_64 musl

      # 构建 musl版 arm64
      - name: Build musl arm64
        run: |
          ./build/build.sh ${{ steps.upstream.outputs.TAG }} arm64 musl

      # 自动发布所有包
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.upstream.outputs.TAG }}-portable
          name: OpenCode ${{ steps.upstream.outputs.TAG }} (Portable)
          files: dist/*.tar.gz
